import type { NextPage } from 'next';
import { Layout } from '../components/layout';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <Layout>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      </Head>      
    </Layout>
  );
};

export default Home;
